### ISSUE TITLE
Contact form doesn't work

### ISSUE THREAD

**Issue by klummy** [FreeCodeCampLagos/FreeCodeCampLagos.github.io#19]
Hello,

The contact form on the page doesn't do anything. 

Two potential solutions:
- The easy way: Use an embed from a form provider e.g. Google Forms etc.
- Tha hard way: Use the form to post data to an API. Maybe use React/Angular/Vue just to make it a tad more complex? :laughing: 

Another option could be to just remove the form and use a button that opens a Google Form or better still a [Form+](https://www.formpl.us/) form.

I am willing to work on any of this options. What approach should we go with?

**Comment by ekpo-d** [comment]
Awesome! Awesome! Awesome thoughts! @klummy 

Our new design doesnt make provision for a  form section. So, i've pulled it down.

Thanks and continue being awesome! :100:
